# Generated by Django 4.2.9 on 2024-01-17 04:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vrexApp', '0011_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolform',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_forms', to=settings.AUTH_USER_MODEL),
        ),
    ]
